project_name: CINI_SmartLightingSystem
version: 1.0

group_members:
        - ovi
        - laura
        - emanuele

statisticsTopologyParams:
  tickTupleFrequency: 60

  hourlyStatistics:
    windowLength: 3600
    emitFrequency: 60

  dailyStatistics:
    windowLength: 86400
    emitFrequency: 3600


queue_out:
  queue_name: 'my-cookye'
  hostname: 'localhost'
  port: 5673

rankingTopologyParams:
  rank_size: 10
  lifetime_minimum: 7

controlThresholds:
  traffic_tolerance: 20
  parking_tolerance: 20
